### ISSUE TITLE
Calculator Test Failed

### ISSUE THREAD

**Issue by Saifulgani** [licanhua/YWinAppDriver#34]
Hi,
The calculator test was failing on my Windows 11 Pro laptop.

Though the Calculator App was launched successfully, I got the below error after launch:

System.InvalidOperationException
  HResult=0x80131509
  Message=Unable to find Windows.UI.Core.CoreWindow|WinUIDesktopWin32WindowClass in {Calculator, ApplicationFrameWindow, }
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Appium.AppiumDriver`1..ctor(Uri remoteAddress, ICapabilities desiredCapabilities)
   at CalculatorTest.CalculatorSession.Setup(TestContext context) in C:\YWinAppDriver\YWinAppDriver-0.3.1.0\examples\CalculatorTest\CalculatorSession.cs:line 42
   at CalculatorTest.ScenarioStandard.ClassInitialize(TestContext context) in C:\YWinAppDriver\YWinAppDriver-0.3.1.0\examples\CalculatorTest\ScenarioStandard.cs:line 94

I had to add else loop after line 54 in UIObjectHelper.cs to make it work
The below is how my code looks now
    ...
    ...
50   if (currentTimeout < 0 && element == null)
51   {
52     throw new UIObjectNotFoundException(
53       $"Timeout after ${timeoutInMilliseconds}: Unable to find {string.Join("|", classNames)} in {topWindow}");
54   }
55   else      // by Saif
56   {
57     break;
58   }
    ...
    ...

Just want a confirmation, is this correct? Or am I missing something?

Thanks,
Saif.

**Comment by daluu** [comment]
Well, did things work with your code change? You could test it out as one way to confirm as well.

**Comment by Saifulgani** [comment]
Yes! My code changes doe work.

**Comment by licanhua** [comment]
First, we need to know why the matching failed. 
1. It maybe the calculator app is changed, and the existing matching is not enough to match the app. The app will always fail in this case, and need code fix it.
2. timeout. The matching depends on a timer. You may workaround the issue either increasing the 300ms timeout
![image](https://github.com/licanhua/YWinAppDriver/assets/6290692/d5ea3c50-4360-4104-bcdf-e100929038ed)
or using title matching
![image](https://github.com/licanhua/YWinAppDriver/assets/6290692/462f6bd3-d97a-4795-8d5f-c3d6a605a781)

**Comment by ZebinGao** [comment]
sorry, I have the same problem. And  I try another way, use location to launch the app:

private const string CalcPath = @"C:\Windows\System32\calc.exe";
appCapabilities.SetCapability("app", CalcPath);

still failed, information:
System.InvalidOperationException:“Process was created, but fail to match a window (InsecureCertificate)”

**Comment by ZebinGao** [comment]
@Saifulgani , my friend, I find one way to fix this error.

1, add one string of classname

<img width="708" height="181" alt="Image" src="https://github.com/user-attachments/assets/86ffbb2b-099f-4078-a559-961d0adddaf4" />

2, add the third classname here

<img width="1064" height="211" alt="Image" src="https://github.com/user-attachments/assets/13467057-fec0-453e-8bb4-336e56b2e39e" />

3, rebuild and try again, the problem is fixed
